function Export-ReportCSV {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)]
        [PSObject]$Data,
        [Parameter(Mandatory=$true)]
        [string]$ReportName
    )

    try {
        $filePath = Join-Path -Path "$PSScriptRoot\..\logs" -ChildPath "$ReportName.csv"
        $Data | Export-Csv -Path $filePath -NoTypeInformation -Force
        Write-Log -Level INFO -Message "CSV report generated: $filePath"
        return $filePath
    }
    catch {
        Write-Log -Level ERROR -Message "Failed to export CSV report: $_"
    }
}

function Export-ReportHTML {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)]
        [PSObject]$Data,
        [Parameter(Mandatory=$true)]
        [string]$ReportName
    )

    try {
        $filePath = Join-Path -Path "$PSScriptRoot\..\logs" -ChildPath "$ReportName.html"
        $html = $Data | ConvertTo-Html -Property * -Title "$ReportName Report" -PreContent "<h1>$ReportName Report</h1>" -PostContent "<footer>Generated by SysAdmin Toolkit</footer>"
        $html | Out-File -FilePath $filePath -Encoding UTF8
        Write-Log -Level INFO -Message "HTML report generated: $filePath"
        return $filePath
    }
    catch {
        Write-Log -Level ERROR -Message "Failed to generate HTML report: $_"
    }
}

function Export-ReportMarkdown {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)]
        [PSObject]$Data,
        [Parameter(Mandatory=$true)]
        [string]$ReportName
    )

    try {
        $filePath = Join-Path -Path "$PSScriptRoot\..\logs" -ChildPath "$ReportName.md"
        $mdContent = "# $ReportName Report`n`n"
        foreach ($item in $Data) {
            $mdContent += "## $($item.PSObject.Properties.Name)`n"
            $mdContent += "$($item | Out-String)`n"
        }
        $mdContent | Out-File -FilePath $filePath -Encoding UTF8
        Write-Log -Level INFO -Message "Markdown report generated: $filePath"
        return $filePath
    }
    catch {
        Write-Log -Level ERROR -Message "Failed to generate Markdown report: $_"
    }
}

